### ISSUE TITLE
Trigger action

### ISSUE THREAD

**Issue by timothepearce** [sietse85/nova-button#1]
Hi @sietse85,

Thank you for your package, I see plenty of use cases where it can be useful.

Do you think it would be possible to add the triggering of an action via a click on the button?

**Comment by sietse85** [comment]
@timothepearce I assume you mean a NovaAction? You can already dispatch actions via a custom event. `Button::make('Approve')->event(ApproveAction::class)`

But yes the action could perhaps also be triggered on the Button class itself. That could be a nice addition. It would of course only work for single resource and not multi-select. 

Feel free to make your own PR, else I will see to add it when I have the time.

**Comment by sietse85** [comment]
@timothepearce  Added in v1.0.10 support to trigger action on the current resource (without ActionFields)

**Comment by timothepearce** [comment]
@sietse85 Sorry for the delay and thank you for the release, I'll use it next week :)
