### ISSUE TITLE
route method is protected

### ISSUE THREAD

**Issue by mihai-stancu** [sietse85/nova-button#14]
Hello,

@dillingham's version supported calling `Button::make(...)->route('route_name', [...])` to link to an arbitrary Laravel route.

I've noticed that in this version the `route` method is protected? Was this deliberate?

**Comment by sietse85** [comment]
@mihai-stancu  iirc it was protected when i started modifying the original version, i don't know why, feel free to adjust it in a PR

**Comment by sietse85** [comment]
merged added v1.0.18
