### ISSUE TITLE
Reload doesn't seem to work

### ISSUE THREAD

**Issue by adammparker** [sietse85/nova-button#15]
Thanks for forking this!

I've got a pretty simple button that calls an event and also uses the `reload()` function. In the console after clicking the button it says "Success" and then does not reload, I think there might not be a reference to the `e.$router.go()` that is being called:

![image](https://user-images.githubusercontent.com/5186174/183494728-3f9c6ce1-125f-485f-b6e3-deb559711af8.png)

**Comment by sietse85** [comment]
@adammparker  which version are you using?

**Comment by adammparker** [comment]
@sietse85 I thought I updated to 1.0.17, but I think I might be on 1.0.14 - I see it's fixed in a more recent version - sorry about that. Let me try and force the update!

**Comment by sietse85** [comment]
Feel free to reopen the issue if it's still not fixed.
