### ISSUE TITLE
Redirect on Action

### ISSUE THREAD

**Issue by codetailor-eu** [sietse85/nova-button#17]
Thanks for your work and the great tool - saved a lot of time!

Yet I encountered one issue, where I´m actually not sure if it can be resolved at all. I have an Action that in some cases returns a Redirect action like this:

return Action::redirect(url('/resources/xxx/' . $related->id));

This redirect is not working when calling the action via your button, on the action menu and the inline actions it works fine.

When I return a message like:
return Action::danger('Not allowed!');

it is displayed correctly, also the button switches to "success"

Is there any way to make the redirect work?

Thanks!
Bastian

**Comment by sietse85** [comment]
I think such a thing can be build in. I could try it when I have some spare time on my hands, else feel free to make a PR.

**Comment by sietse85** [comment]
@itbul support for redirects added in v1.0.19

**Comment by codetailor-eu** [comment]
Great, thanks a lot for adding this!

**Comment by sietse85** [comment]
@itbul you can thank @marcorivm who added it
