### ISSUE TITLE
route does not exist

### ISSUE THREAD

**Issue by adityadees** [sietse85/nova-button#2]
![image](https://user-images.githubusercontent.com/37553901/171673995-7b9d48fe-dec9-41c9-83fd-937ec2c18488.png)

this my configuration 

![image](https://user-images.githubusercontent.com/37553901/171674127-cded21c6-24af-470c-bb8c-84da2370a91a.png)

**Comment by sietse85** [comment]
@adityadees `route` is a protected method, you can use `link` to link to pages outside of Nova. Next to that you can also use the `create` `index` `edit` `lens` routes to make links to Nova resources.

I will need to update the readme with this information it seems.
