### ISSUE TITLE
Action Buttton does not appear

### ISSUE THREAD

**Issue by DockerComposeFiles** [sietse85/nova-button#24]
The Buttons will Actual not displayed.

Button::make('Visit')
![image](https://user-images.githubusercontent.com/87118951/209320629-da10e470-078e-424e-a2f5-49a7de649408.png)

"sietse85/nova-button": "^1.0"
Nova v4.19.5 (Silver Surfer)

When click the empty row, the details are open.

**Comment by sietse85** [comment]
@DockerComposeFiles  can't reproduce, did you publish default styles?

**Comment by DockerComposeFiles** [comment]
Yes I published the assets

currently the buttons will works and outputs text without style

![image](https://user-images.githubusercontent.com/87118951/210208105-0de749df-3b43-4551-9750-6436e967e526.png)

[composer.txt](https://github.com/sietse85/nova-button/files/10330581/composer.txt)

seems the probem is at tailwind
