### ISSUE TITLE
Adding classes only with array possible

### ISSUE THREAD

**Issue by DockerComposeFiles** [sietse85/nova-button#25]
The Tailwind Styling Wrapper raises an error

` Button::make('Visit')->classes('nova-button-success'),`

_array_merge(): Argument #2 must be of type array, string given_

on
vendor / sietse85 / nova-button / src / Button.php : 372

when not put an array to the method:
`Button::make('Visit')->classes(['nova-button-success']),`

It needs auto convert strings to array or correcting the dosc

**Comment by sietse85** [comment]
@DockerComposeFiles  where in the docs you read you can use strings?
