### ISSUE TITLE
Feature request: allow events to process before navigating to links

### ISSUE THREAD

**Issue by shawnheide** [sietse85/nova-button#26]
Hello, thanks for your work on this project, it really helped in getting upgraded to Nova 4. One issue I found is that when you have a link set for the button, the events aren't sent. It looks like this has to do with returning after the `this.navigate` is called here: https://github.com/sietse85/nova-button/blob/b12b9115c41510058170c43018efa7f991a90169/resources/js/components/NovaButton.vue#L48

Processing the events before the link seems to be how dillingham/nova-button worked, but it looks like you changed it in this commit: ba303a7c8e67806a1e7f53461404112147940533. Would you consider allowing this again if I submit a PR? Any other thoughts or preferences with it?

**Comment by sietse85** [comment]
@shawnheide afaik routing links and nova internal links was entirely broken in the old package. but be my guest i would gladly accept the PR if it makes links work after events are sent.
