### ISSUE TITLE
Passing Additional Data to Event Listener

### ISSUE THREAD

**Issue by sagadsalem** [sietse85/nova-button#28]
Hi 
First Thanks for The Great Work,

I Have use case where I need to pass additional data to the event not only the selected resource how I can do this?

**Comment by sietse85** [comment]
> Hi First Thanks for The Great Work,
> 
> I Have use case where I need to pass additional data to the event not only the selected resource how I can do this?

Can't you add the additional data to your resource model?

**Comment by sagadsalem** [comment]
No, it's not a resource data

For example
Student Resource
Workshop Resource

when I use the package on the student resource and need to pass the selected workshop ID I can't do it, because all I can pass is the student data.

**Comment by sietse85** [comment]
yes you can only use data from the resource, passing additional data from any field is not supported.
