### ISSUE TITLE
passing data with link

### ISSUE THREAD

**Issue by adityadees** [sietse85/nova-button#3]
Last time I open Issue if route does not exist, I following the `Readme.md`
I want to ask, do you have any documentation for pass parameter or data based on input field?
I mean on nova we have default button 'Submit' to save it on DB
Can this Packages Button do action like default submit button nova?
So, I want to create button using this package to save the data on Table A
and default nova button to save data on Table B
It's possible for do it?

**Comment by sietse85** [comment]
@adityadees  this package is not meant as a replacement for Nova's default create/save etc buttons. You can make links and supply parameters to them using the `link` method for outside of nova and `create` `detail` `index` methods for routes inside nova.

**Comment by adityadees** [comment]
> @adityadees this package is not meant as a replacement for Nova's default create/save etc buttons. You can make links and supply parameters to them using the `link` method for outside of nova and `create` `detail` `index` methods for routes inside nova.

no, I don't mean replace. What I mean is whether this button can have a similar function like the nova button which when pressed can save data?
The different is only for the route.
Since default button I want to use for save to Table B
and this button package I want to use for save to Table A

as you say we can use link for external route, and can I use post or put method route and send the data from the input field, so we can store it on DB?
I need the documentation if it's possible

**Comment by sietse85** [comment]
@adityadees this package does not provide such functionality. Perhaps it can be build in, but I would have to research that when I have some time.
