### ISSUE TITLE
Adding ability to style confirmation popup buttons

### ISSUE THREAD

**Issue by Pixel-Tony** [sietse85/nova-button#30]
Hello and many thanks for such a wonderful button, it saved us quite a lot of time during development!

At the moment it is only possible for "press processing" and "finished" states to have their button styles changed, but I think it would be more convenient to also allow styling of initial popup buttons.
The main issue is, while using Nova's light theme, "Confirm" button's background is overridden by internal Nova theme rules. Thus, white text inside of it appears invisible on white popup's background.

**Comment by sietse85** [comment]
@Pixel-Tony  you can add styles now (v1.0.26)

`// One class
Button::make('Notify')->confirm('sure?')->modalClasses(['some-class'])

// Or multiple classes
Button::make('Notify')->confirm('sure?')->modalClasses(['some-class', 'another-class'])`
