### ISSUE TITLE
download action dont work

### ISSUE THREAD

**Issue by sitnikov** [sietse85/nova-button#32]
action response with

{
    "download": "\/nova-api\/messages\/261\/download\/store_filename",
    "name": "message-0001-99dfb9f0-4961-47d8-a62c-7a6daa964330.eml"
}

**Comment by sietse85** [comment]
@sitnikov you've got to provide more info then just this. what did you make for a button? what do you expect it todo?

**Comment by sitnikov** [comment]
try use button with this

https://nova.laravel.com/docs/4.0/actions/defining-actions.html#download-responses

**Comment by sietse85** [comment]
@sitnikov  this is not helpful, what are you trying todo, show some code? How is the problem related to this package? The Button::action method is limited to 1 resource only at a time, without supporting fields.

**Comment by sitnikov** [comment]
Try 

```
public function handle(ActionFields $fields, Collection $models)
{
  return Action::download('https://example.com/invoice.pdf', 'Invoice.pdf');
}
```

**Comment by sietse85** [comment]
@sitnikov  if you have issues with Laravel Nova you can submit a bug here:
**https://github.com/laravel/nova-issues**

**Comment by sitnikov** [comment]
this is ok without button action

**Comment by sietse85** [comment]
@sitnikov  if you mean to download a file with the button you can use the `Route` method for it
`Button::make('Download')->route('/getFile')` or something

**Comment by sitnikov** [comment]
Action::download() - default feature

**Comment by sietse85** [comment]
@sitnikov converting json response from action as download to an actual download is not supported currently is this package, not via the `action` method. You could use the `route` method to achieve this instead like I showed in previous comment.

**Comment by sitnikov** [comment]
but action must generate this file before download ...
