### ISSUE TITLE
Action button cannot be clicked a 2nd time without reloading the page.

### ISSUE THREAD

**Issue by vesper8** [sietse85/nova-button#33]
Hello! First of all thanks a lot for making this. It works really well and I'm enjoying using it.

Small nitpick.. I've noticed that when you click a button that triggers an action, the button initially displays as a button but after clicking it the button vanishes and is replaced by text, in my case it says 'success'. If I try to click it a second time, instead of triggering the action again, it goes to the resource view page. Or if I'm already on the resource view page, then clicking it a 2nd time just does nothing.

I would prefer it if it remained as a button and could be clicked as many times as needed.

is there any way to modify this behaviour? 

Many thanks!!

**Comment by sietse85** [comment]
@vesper8 Have you tried `->reload()` ? That will reload after the event has finished.

**Comment by vesper8** [comment]
Thank you! Yes that does indeed work!

My button now looks like this

```
            Button::make('Inspect in Lessons Summary Calendar')
                ->style('success')
                ->action(InspectInCalendar::class)
                ->reload(),
```

And I can now click it time and time again. Cheers!
