### ISSUE TITLE
I get error submitting the form if button is being shown on some views

### ISSUE THREAD

**Issue by manuglopez** [sietse85/nova-button#34]
I have created a button to trigger an event, if this button is showed in the creation view or update view it cause an error difficult to debug because  'There was a problem submitting the form'  it does not log any error and nor cause 500 error. 

Anyway with the next options it works fine

```
Button::make('Notificar a Telegram')
                        ->style('primary')
                        ->event(\App\Events\UsuarioUpdatedOrCreated::class)
                        ->showOnIndex(false)
                        ->showOnDetail(),
```

**Comment by sietse85** [comment]
This is not something I can work with. It is not even clear if the problem is in this package or in your own code. Please reopen if you have additional info,
