### ISSUE TITLE
Problem with the vuejs 

### ISSUE THREAD

**Issue by YordanY1** [sietse85/nova-button#35]
Uncaught ReferenceError: Vue is not defined
    6511 http://127.0.0.1:8000/nova-api/scripts/nova-button:1
    n http://127.0.0.1:8000/nova-api/scripts/nova-button:1
    <anonymous> http://127.0.0.1:8000/nova-api/scripts/nova-button:1
    O http://127.0.0.1:8000/nova-api/scripts/nova-button:1
    <anonymous> http://127.0.0.1:8000/nova-api/scripts/nova-button:1
    <anonymous> http://127.0.0.1:8000/nova-api/scripts/nova-button:1

**Comment by sietse85** [comment]
Sorry I cannot see how this is a problem with this package. Provide more details if you want me to take a look.
