### ISSUE TITLE
use click button link error

### ISSUE THREAD

**Issue by adityadees** [sietse85/nova-button#8]
![image](https://user-images.githubusercontent.com/37553901/172406026-6b16721e-b842-487b-bdc5-a02207bb3bbc.png)

this my code, I'm getting error when I click the button, last time when I open Issue this working fine, the only problem is I cannot save it on Updating or on Creating

`Button::make('Preview', 'posts_preview_button')->style('warning')->link(route('blog_preview') . '?id=' . $this->posts_id)
                ->showOnCreating()->showOnUpdating(),`

**Comment by sietse85** [comment]
probably had todo with #7 , fixed in v1.0.13, please let me know if you have any issues after updating to v1.0.13

**Comment by adityadees** [comment]
still not working. 
Now I'm rollback to v 1.0.5

**Comment by sietse85** [comment]
`->showOnCreating()->showOnUpdating()` this will not work in any version @adityadees you cannot use this on form

**Comment by adityadees** [comment]
I've see the packages from 'ebess/advance-nova-media-library'
![image](https://user-images.githubusercontent.com/37553901/172612648-84d1bd3d-7a14-4728-b824-fe17f4b0450f.png)

he can still save the form with button inside the form
![image](https://user-images.githubusercontent.com/37553901/172612925-da9d966d-6d81-4322-b695-d28828cba521.png)

can this package support the button like that?

**Comment by sietse85** [comment]
no

**Comment by sietse85** [comment]
@adityadees  the bug with the `link` should now be fixed in v1.0.14
